# Generated by Django 4.2.8 on 2024-02-13 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=126, verbose_name='title of the post')),
                ('descriptions', models.TextField(blank=True, max_length=526, null=True, verbose_name='descriptions of the post')),
                ('created', models.DateField(auto_now_add=True, verbose_name='creted date')),
                ('image', models.ImageField(upload_to='post_img/', verbose_name='imge post')),
                ('watch_count', models.IntegerField(default=0, verbose_name='prosmotr')),
                ('like_count', models.IntegerField(default=0, verbose_name='likes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
