# Generated by Django 4.2.8 on 2024-02-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('img', models.ImageField(upload_to='category_img/', verbose_name='img')),
            ],
            options={
                'verbose_name': 'Categorys',
                'verbose_name_plural': 'Categorys',
            },
        ),
    ]
